name: Create PDF

on:
  push:
    branch:
      - main
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Cache typst
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/typst
          key: ${{ runner.os }}-typst
      - name: Install typst
        run: |
          wget https://github.com/typst/typst/releases/download/v0.12.0/typst-x86_64-unknown-linux-musl.tar.xz
          tar xvf typst-x86_64-unknown-linux-musl.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: *.pdf
          compression-level: 0
